spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/myrealm
          jwk-set-uri: http://localhost:9090/realms/myrealm/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      resource-id: stohirov
      principle-attribute: preferred_username