spring:
  application:
    name: ${APP_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/myrealm
          jwk-set-uri: http://localhost:9090/realms/myrealm/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT}

jwt:
  auth:
    converter:
      resource-id: stohirov
      principle-attribute: preferred_username
