ALTER TABLE contacts ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE contacts ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT NOW();